# Generated by Django 4.1.6 on 2023-02-28 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplateform_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='created',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 6, 21, 29, 55114)),
        ),
    ]
