# Generated by Django 4.1.6 on 2023-02-28 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_remove_watchlist_created_watchlist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='streaming_plateform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='streamplateform', to='watchlist_app.streamplateform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 10, 14, 11, 171042)),
        ),
    ]
